version: '3.8'

services:

  backend:
    build:
      context: ./node-js-server
      dockerfile: Dockerfile
    image: jackedcoder/node-backend:latest
    container_name: node-backend
    restart: always
    env_file:
      - .env                        
    ports:
      - "3000:3000"
    networks:
      - backend_network
    
  frontend:
    build:
      context: ./angular-10-client
      dockerfile: Dockerfile
    image: jackedcoder/ang-frontend:latest
    container_name: ang-frontend
    restart: always
    ports:
      - "80:80"
    networks:
      - backend_network

networks:
  backend_network:
    driver: bridge

volumes:
  mysql_data:
    driver: local
