apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: mean-app
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: root
  MYSQL_DATABASE: mean-app
  MYSQL_USER: root
  MYSQL_PASSWORD: root